export const data = [
  {
      "id": 1,
      "name": "Rose",
      "category": "Flowering Plants",
      "description": "Roses are one of the most popular and well-known ornamental plants. They are prized for their beauty and fragrance.",
      "price": 10.99,
      "availability": "In Stock",
      "size": "Medium",
      "light_requirements": "Full Sun",
      "watering_requirements": "Moderate Water",
      "soil_type": "Loamy",
      "img": "https://bs.plantnet.org/image/o/afc9f4d7ce137f04746413f629330948b73e79d3"
  },
  {
      "id": 2,
      "name": "Jasmine",
      "category": "Flowering Plants",
      "description": "Jasmine is a fragrant flowering plant that is prized for its beauty and scent. It is commonly used in perfumes and teas.",
      "price": 7.99,
      "availability": "In Stock",
      "size": "Small",
      "light_requirements": "Partial Sun",
      "watering_requirements": "Low Water",
      "soil_type": "Sandy",
      "img": "https://bs.plantnet.org/image/o/799816cf93b96cb5b89aae91b012150459cfb84a"
  },
  {
      "id": 3,
      "name": "Bougainvillea",
      "category": "Flowering Plants",
      "description": "Bougainvillea is a popular ornamental plant that is prized for its brightly colored flowers. It is often used as a climbing vine or in hanging baskets.",
      "price": 14.99,
      "availability": "In Stock",
      "size": "Large",
      "light_requirements": "Full Sun",
      "watering_requirements": "Low Water",
      "soil_type": "Sandy",
      "img": "https://bs.plantnet.org/image/o/1fa4dec70b727efbb1ea39a10ba07d5191fd299c"
  },
  {
      "id": 4,
      "name": "Hibiscus",
      "category": "Flowering Plants",
      "description": "Hibiscus is a beautiful flowering plant that is prized for its large, colorful blooms. It is often used in gardens and as a houseplant.",
      "price": 9.99,
      "availability": "In Stock",
      "size": "Medium",
      "light_requirements": "Full Sun",
      "watering_requirements": "Moderate Water",
      "soil_type": "Loamy",
      "img": "https://bs.plantnet.org/image/o/a2b8cb049d071ed0bae3d324f7516b794399c4c8"
  },
  {
      "id": 5,
      "name": "Geranium",
      "category": "Flowering Plants",
      "description": "Geraniums are a popular garden plant, known for their bright colors and long blooming season. They come in a variety of colors and sizes, and are easy to care for.",
      "price": 7.99,
      "availability": "In Stock",
      "size": "Small",
      "light_requirements": "Full Sun",
      "watering_requirements": "Moderate Water",
      "soil_type": "Well-Draining",
      "img": "https://bs.plantnet.org/image/o/681b874be13f040bcb3f03f743a51393902e0c9a"
  },
  {
    "id": 6,
    "name": "Oleander",
    "category": "Flowering Plants",
    "description": "Oleander is a popular shrub with beautiful flowers. However, it is toxic and should be handled with care.",
    "price": 8.99,
    "availability": "In Stock",
    "size": "Large",
    "light_requirements": "Full Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Sandy",
    "img": "https://bs.plantnet.org/image/o/2ff93222759bd7436338492c834074bba64948f4"
},
{
    "id": 7,
    "name": "Iris",
    "category": "Bulbs",
    "description": "Iris is a beautiful bulbous plant with distinctive flowers. They come in a variety of colors and are easy to grow.",
    "price": 5.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Drained",
    "img": "https://bs.plantnet.org/image/o/043ebfc31ccb2999b3354a7fc2626c061d00b5f3"
},
{
    "id": 8,
    "name": "Pansy",
    "category": "Annual Plants",
    "description": "Pansies are a popular bedding plant known for their colorful, heart-shaped flowers. They are easy to grow and can bloom in both spring and fall.",
    "price": 3.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Loamy",
    "img": "https://bs.plantnet.org/image/o/eb67e6fc66875ab4fe312007eafa9e163f76a003"
},
{
    "id": 9,
    "name": "Petunia",
    "category": "Annual Plants",
    "description": "Petunias are a popular bedding plant with trumpet-shaped flowers. They come in a variety of colors and can bloom throughout the summer.",
    "price": 4.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Loamy",
    "img": "https://bs.plantnet.org/image/o/96b7d99dca3781982ed1e81e9192f3bad897e9a6"
},
{
    "id": 10,
    "name": "Marigold",
    "category": "Flowering Plants",
    "description": "Marigolds are easy-to-grow annual plants that are prized for their bright, showy flowers. They come in a variety of colors and can be used in borders, beds, and containers.",
    "price": 5.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/131ea9453e712152185915dc0a205272ebe15285"
},
{
    "id": 11,
    "name": "Sunflower",
    "category": "Flowering Plants",
    "description": "Sunflowers are tall, bold annual plants that produce large, showy flowers. They are easy to grow and are often used in gardens and as cut flowers.",
    "price": 8.99,
    "availability": "In Stock",
    "size": "Large",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/e92bdbc5adc4e91cc0c5aa8e9f102833a28bc6e3"
},
{
    "id": 12,
    "name": "Zinnia",
    "category": "Flowering Plants",
    "description": "Zinnias are popular annual plants that come in a wide variety of colors and sizes. They are easy to grow and are often used in borders, beds, and containers.",
    "price": 6.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/b39902fe640eaa94188ccf3af7a55fb115029fac"
},
{
    "id": 13,
    "name": "Daffodil",
    "category": "Flowering Plants",
    "description": "Daffodils are popular spring-blooming bulbs that produce large, showy flowers. They are easy to grow and are often used in gardens and as cut flowers.",
    "price": 12.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/9b007c6fe4df23916fe770fd52579f126863bb92"
},
{
    "id": 14,
    "name": "Narcissus",
    "category": "Bulbous Plants",
    "description": "Narcissus is a genus of predominantly spring flowering perennial plants of the Amaryllidaceae family.",
    "price": 8.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Low to Moderate Water",
    "soil_type": "Well-drained, Loamy",
    "img": "https://bs.plantnet.org/image/o/41ca1cb436127c932428ce6a8a742fadb47de0dd"
},
{
    "id": 15,
    "name": "Tulip",
    "category": "Bulbous Plants",
    "description": "Tulips are a genus of spring-blooming perennial herbaceous bulbiferous geophytes.",
    "price": 12.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-drained, Loamy",
    "img": "https://bs.plantnet.org/image/o/5bf2df74894d7c49cb4faf73f5f536a123ee8089"
},
{
    "id": 16,
    "name": "Hyacinth",
    "category": "Bulbous Plants",
    "description": "Hyacinths are spring-blooming bulbs with fragrant flowers. They are often used for garden decoration or as indoor plants.",
    "price": 9.99,
    "availability": "In Stock",
    "size": "Small to Medium",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Low to Moderate Water",
    "soil_type": "Well-drained, Loamy",
    "img": "https://bs.plantnet.org/image/o/5854119576866163bdb4d5c86cc3e3caf89287a3"
},
{
    "id": 17,
    "name": "Fuchsia",
    "category": "Flowering Plants",
    "description": "Fuchsias are popular garden plants, grown for their very attractive, usually pendent flowers that are borne in summer and autumn.",
    "price": 7.99,
    "availability": "In Stock",
    "size": "Medium to Large",
    "light_requirements": "Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-drained, Humus-rich",
    "img": "https://bs.plantnet.org/image/o/1b5333130f60456428da7aa2e55aa037d2fa87df"
},
{
    "id": 18,
    "name": "Lavender",
    "category": "Herbs",
    "description": "Lavender is a fragrant herb that is commonly used in perfumes, soaps, and other personal care products.",
    "price": 6.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Well-Draining",
    "img": "https://bs.plantnet.org/image/o/010ffc8860641c73888c8664743f1527d284f258"
},
{
    "id": 19,
    "name": "Sage",
    "category": "Herbs",
    "description": "Sage is a popular herb that is often used in cooking, particularly in Mediterranean and Middle Eastern cuisines.",
    "price": 5.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Well-Draining",
    "img": "https://bs.plantnet.org/image/o/ba565945528a0f63276ac76495e7e1cd3d47e127"
},
{
    "id": 20,
    "name": "Mint",
    "category": "Herbs",
    "description": "Mint is a versatile herb that is commonly used in teas, desserts, and other culinary creations.",
    "price": 4.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Partial Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Moist",
    "img": "https://bs.plantnet.org/image/o/04fdf5bbfec0530275456e500ef895fd02514de6"
},
{
    "id": 21,
    "name": "Basil",
    "category": "Herbs",
    "description": "Basil is a fragrant herb that is used in a variety of cuisines, including Italian, Thai, and Vietnamese.",
    "price": 7.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": "https://bs.plantnet.org/image/o/eaf722de31333a8724b4bb72c8d51959530fae56"
},
{
    "id": 22,
    "name": "Thyme",
    "category": "Herbs",
    "description": "Thyme is a fragrant herb that is commonly used in Mediterranean and Middle Eastern cuisine.",
    "price": 4.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/e79e18ec848b7684986f5a9fdb2ad1044993f7b3"
},
{
    "id": 23,
    "name": "Oregano",
    "category": "Herbs",
    "description": "Oregano is a popular herb that is often used in Italian and Greek dishes.",
    "price": 5.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/06ee8acbdaa5778cbc62f93fb2709f6896c1f754"
},
{
    "id": 24,
    "name": "Rosemary",
    "category": "Herbs",
    "description": "Rosemary is a versatile herb that is commonly used in Mediterranean cuisine and is known for its aromatic and flavorful leaves.",
    "price": 6.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/45c47e31c6a0c5378581f0bc89c0b44405868dd1"
},
{
    "id": 25,
    "name": "Chives",
    "category": "Herbs",
    "description": "Chives are a mild-flavored herb that is often used in French cuisine and are characterized by their long, thin leaves.",
    "price": 3.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun to Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/5e033417dbfff7e86535bd7f431bb4162804a0c9"
},
{
    "id": 26,
    "name": "Parsley",
    "category": "Herbs",
    "description": "Parsley is a versatile herb used in a wide variety of dishes. It is rich in vitamins and minerals.",
    "price": 4.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/0b5da0fbeb0e2dc33ad8ab8de2fa0aa6f169076c"
},
{
    "id": 27,
    "name": "Coriander",
    "category": "Herbs",
    "description": "Coriander is a popular herb used in many different cuisines. It is known for its unique flavor and aroma.",
    "price": 5.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/40240f910a87c4f26ccbbe9ec22767297bb8e277"
},
{
    "id": 28,
    "name": "Cactus",
    "category": "Succulents",
    "description": "Cacti are low-maintenance plants that are perfect for busy people. They come in a wide variety of shapes and sizes.",
    "price": 12.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Infrequent Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/a106e0b8f659e61f1370534d8aeb724bbbb23ab1"
},
{
    "id": 29,
    "name": "Aloe Vera",
    "category": "Succulents",
    "description": "Aloe vera is a popular plant known for its healing properties. It is easy to care for and can be used in a variety of ways.",
    "price": 14.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Infrequent Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/170cc12d490078fc218c45d6ea2f76546b44d416"
},
{
    "id": 30,
    "name": "Pothos",
    "category": "Indoor Plants",
    "description": "Pothos is a low-maintenance trailing plant that can be grown in a variety of lighting conditions. Its leaves come in a variety of shades, including green, yellow, and variegated.",
    "price": 12.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Low to Medium Light",
    "watering_requirements": "Low Water",
    "soil_type": "Well-Draining",
    "img": "https://bs.plantnet.org/image/o/5b26070f9c1e29609e0ff022a7411b9b02bb6c16"
},
{
    "id": 31,
    "name": "Spider Plant",
    "category": "Indoor Plants",
    "description": "Spider plants are popular for their long, thin foliage and small white flowers. They are easy to grow and can thrive in a variety of environments.",
    "price": 9.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Bright to Medium Light",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": "https://bs.plantnet.org/image/o/b8a8307ca3ae5e12cf13458c88b343d951dbb0f4"
},
{
    "id": 32,
    "name": "Snake Plant",
    "category": "Indoor Plants",
    "description": "Snake plants are known for their tall, sturdy leaves and ability to thrive in low-light conditions. They are also known for their air-purifying properties.",
    "price": 14.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Low to Bright Light",
    "watering_requirements": "Low Water",
    "soil_type": "Well-Draining",
    "img": "https://storage.googleapis.com/powop-assets/lowo/KLOWO_147_fullsize.jpg"
},
{
    "id": 33,
    "name": "Dracaena",
    "category": "Indoor Plants",
    "description": "Dracaena is a popular houseplant with long, narrow leaves that come in a variety of colors, including green, yellow, and red. It is a low-maintenance plant that can thrive in a variety of lighting conditions.",
    "price": 16.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Low to Bright Light",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": "https://bs.plantnet.org/image/o/76fd49d0e59be91b7bebab9e8cc0ad6349b562c4"
},
{
    "id": 34,
    "name": "Peace Lily",
    "category": "Indoor Plants",
    "description": "The Peace Lily is a popular indoor plant known for its ability to improve air quality and remove toxins from the air.",
    "price": 25.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Low to Medium Light",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": "https://bs.plantnet.org/image/o/4ab84c138c643fb6275e24a87727c439ffc805b1"
},
{
    "id": 35,
    "name": "English Ivy",
    "category": "Indoor Plants",
    "description": "English Ivy is a popular trailing plant with small, pointed leaves that are often variegated. It is a great choice for indoor hanging baskets or to climb walls.",
    "price": 20.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Low to Medium Light",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": "https://storage.googleapis.com/powop-assets/kew_profiles/Hedera-helix_fullsize.jpg"
},
{
    "id": 36,
    "name": "Croton",
    "category": "Indoor Plants",
    "description": "Crotons are tropical plants known for their colorful foliage. They are great for adding a pop of color to your indoor space.",
    "price": 30.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "High Light",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": "https://bs.plantnet.org/image/o/21d1de8960e575a4736ccd2ddca1377e4c4b3632"
},
{
    "id": 37,
    "name": "Rubber Plant",
    "category": "Indoor Plants",
    "description": "The Rubber Plant is a popular indoor plant known for its large, shiny leaves. It can grow up to 8 feet tall and requires moderate watering.",
    "price": 24.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Medium to High Light",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining soil",
    "img": "https://bs.plantnet.org/image/o/21b7dab48594def004c2c7117fd614790ad196d6"
},
{
    "id": 38,
    "name": "Amaryllis",
    "category": "Flowering Plants",
    "description": "The Amaryllis is a beautiful flowering plant that blooms in the winter. It comes in many colors and can grow up to 2 feet tall.",
    "price": 12.99,
    "availability": "Out of Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining soil",
    "img": "https://bs.plantnet.org/image/o/a15b91aa49915a88a1648853690c8a290096bb3b"
},
{
    "id": 39,
    "name": "Cyclamen",
    "category": "Flowering Plants",
    "description": "The Cyclamen is a popular indoor plant known for its beautiful, brightly colored flowers. It requires cool temperatures and moderate watering.",
    "price": 18.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Medium to High Light",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining soil",
    "img": "https://bs.plantnet.org/image/o/21dabd7eef67c8a017a782373ba74ca357656320"
},
{
    "id": 40,
    "name": "Chrysanthemum",
    "category": "Flowering Plants",
    "description": "The Chrysanthemum is a popular outdoor plant known for its beautiful, colorful flowers. It requires full sun and moderate watering.",
    "price": 8.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining soil",
    "img": "https://bs.plantnet.org/image/o/1af9f3fb7b792d6568892cd529520625d0ed0106"
},
{
    "id": 41,
    "name": "Delphinium",
    "category": "Flowering Plants",
    "description": "Delphinium is a tall and elegant flowering plant known for its long spikes of blue or purple flowers. It is a popular choice for cottage gardens.",
    "price": 12.99,
    "availability": "In Stock",
    "size": "Large",
    "light_requirements": "Full Sun to Partial Shade",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/08e61830ac41c8f4fa51ce752fc119abde564740"
},
{
    "id": 42,
    "name": "Phlox",
    "category": "Flowering Plants",
    "description": "Phlox is a low-growing plant that produces clusters of small, fragrant flowers in shades of pink, purple, and white. It is a great choice for rock gardens or as a ground cover.",
    "price": 9.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/e37daf64f8ee89e1a544a1bc04a8d820ea9d6d48"
},
{
    "id": 43,
    "name": "Sweet Pea",
    "category": "Flowering Plants",
    "description": "Sweet pea is a climbing plant that produces clusters of fragrant flowers in shades of pink, purple, and white. It is a great choice for trellises or arbors.",
    "price": 11.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun to Partial Shade",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/2ceed94d3efadc76f6480c964b105086f60a594b"
},
{
    "id": 44,
    "name": "Gardenia",
    "category": "Flowering Plants",
    "description": "Gardenia is a flowering plant known for its large, fragrant white flowers. It is a popular choice for indoor and outdoor gardens.",
    "price": 14.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Partial Shade",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/4115409bdbda75e134ac40bedd70be369b95a49d"
},
{
    "id": 45,
    "name": "Stock",
    "category": "Flowering Plants",
    "description": "Stocks are prized for their delicate, sweetly scented flowers that come in shades of pink, purple, white, and red.",
    "price": 8.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/5c5d04154e85a1f0f6474f5229addcf83ba823e6"
},
{
    "id": 46,
    "name": "Crocus",
    "category": "Bulbs",
    "description": "Crocuses are small, hardy bulbs that bloom in late winter to early spring, providing a welcome burst of color after the winter months.",
    "price": 6.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/40a10e331a47165f3d8f809f63cc5082336af91f"
},
{
    "id": 47,
    "name": "Scabiosa",
    "category": "Flowering Plants",
    "description": "Scabiosas are popular garden plants that are known for their dainty, pin-cushion-like flowers that come in shades of pink, purple, and white.",
    "price": 9.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining",
    "img": "https://bs.plantnet.org/image/o/c204600bf1f260059e96d5d63120d2b87b6ed5b5"
},
{
    "id": 48,
    "name": "Anemone",
    "category": "Flowering Plants",
    "description": "Anemones are beautiful, delicate flowers that bloom in a range of colors. They are often used in floral arrangements and can add a touch of elegance to any garden.",
    "price": 5.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": "https://bs.plantnet.org/image/o/4ba485bce6cb2c80f13b6695c29501ceb37c2f65"
},
{
    "id": 49,
    "name": "Lemon Plant",
    "category": "Fruit Trees",
    "description": "Lemon trees are a popular choice for home gardens due to their delicious fruit and beautiful appearance. They require a sunny spot and moderate watering to thrive.",
    "price": 29.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": "https://bs.plantnet.org/image/o/99fdebdcb39e78a525136006c79cf4e9f8e4f928"
}
]
